
init:
- appveyor version
- sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
- sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
- sh: gvm use go1.4
- sh: lsb_release -sr

test_script:
- sh: |
    RED='\033[0;31m'
    NC='\033[0m'
    FLAG=false
    for cmd in wget curl 7z 7za ftp lftp tclsh \
    cmake make mvn gradle ant yarn \
    gcc gfortran java javac go nodejs ruby \
    docker sqlcmd psql mongo rabbitmqctl packer aws localstack az \
    pwsh mono mcs xsp4 csc \
    pip virtualenv python python3 \
    git svn hg
    do 
      command -v $cmd || { echo -e "$RED$cmd NOT FOUND!$NC"; FLAG=true; }
    done
    set -x
    if [[ $(lsb_release -sr) = '16.04' ]]; then
      for cmd in easy_install
      do
        command -v $cmd || { echo -e "$RED$cmd NOT FOUND!$NC"; FLAG=true; }
      done
    fi
    set +x
    if $FLAG; then
      return 1
    else
      return 0
    fi
    
build: off
